# Generated by Django 4.0 on 2023-11-29 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel1_data',
            name='user',
        ),
        migrations.RemoveField(
            model_name='channel2_data',
            name='user',
        ),
        migrations.RemoveField(
            model_name='channel3_data',
            name='user',
        ),
    ]
